version: '3.7'
services:
  geoip:
    image: geoip
    build:
      context: service
      target: devel
    ports:
      - '3000:3000'
    environment:
      - NODE_CONFIG=development
    volumes:
      - './service:/opt/service'
    depends_on:
      - db

  db:
    image: mysql/mysql-server:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=devel
      - DB_REMOTE_ROOT_NAME=root
      - DB_REMOTE_ROOT_PASS=devel
    ports:
      - '3306:3306'
    volumes:
      - './data:/var/lib/mysql'
